spring:
  application:
    name: lotto
  datasource:
    # url: ${DB_URL}
    # username: ${DB_USERNAME}
    # password: ${DB_PASSWORD}
    url: jdbc:mariadb://localhost:3306/lotto_event
    username: lotto_app
    password: passw0rd
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.otr.lotto
  configuration:
    map-underscore-to-camel-case: true

lottery:
  first-prize-phone: ${LOTTERY_FIRST_PRIZE_PHONE:010-1234-5678}
  first-prize-numbers: ${LOTTERY_FIRST_PRIZE_NUMBERS:3,11,22,33,41,45}
